version: '3.8'

services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@database:5432/mydatabase
    depends_on:
      - database

volumes:
  db_data:
